version: 2.1

orbs:
  secrethub: marton/test-s@dev:alpha

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - secrethub/secrethub-run:
          command: pwd
      - secrethub/secrethub-run:
          command: ls
      - secrethub/secrethub-run:
          command: node test.js
