version: 2.1

orbs:
  secrethub: marton/test-s@dev:alpha

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - secrethub/install
      - checkout
      - run: ls -la /usr/bin
      - run: ls -la
      - run: secrethub run -- node test.js
