version: 2.1

orbs:
  secrethub: secrethub/cli@dev:first

jobs:
  build:
    shell: secrethub run --no-masking -- /bin/bash
    docker:
      - image: circleci/node:latest
        environment:
          DB_PASS: secrethub://marton/test1/password
          DB_USER: test_user
          DB_HOST: localhost

    steps:
      - secrethub/install
      - checkout
      - run: node test.js
