version: 2.1

jobs:
  build:
    shell: ./secrethub run -- /bin/bash
    docker:
      - image: circleci/node:latest
        environment:
          DB_PASS: secrethub://marton/test1/password
          DB_USER: test_user
          DB_HOST: localhost

    steps:
      - checkout
      - run: node test.js
