version: 2.1

orbs:
  secrethub: marton/test-s@dev:alpha

jobs:
  build:
    shell: secrethub run -- /bin/bash
    docker:
      - image: circleci/node:latest
    steps:
      - secrethub/install
      - checkout
      - run: node test.js
