version: 2.1

orbs:
  secrethub: marton/test-s@dev:alpha

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - secrethub/secrethub-run:
          command: secrethub ls marton/test1
      - run: secrethub ls marton/test1
