version: 2.1

jobs:
  build:
    # shell: secrethub run -- /bin/bash
    docker:
      - image: circleci/golang:latest
        environment:
          TEST: secrethub://marton/test1/password
    steps:
      - run: git clone https://github.com/secrethub/secrethub-cli.git
      - run: go build ./secrethub-cli/cmd/secrethub
      - run: rm -rf ./secrethub-cli
      - run: sudo mv ./secrethub /usr/local/bin
      - checkout
      - run: secrethub run -- echo ${#TEST}
